[package]
name = "sol-eyre"
edition.workspace = true
authors.workspace = true
documentation.workspace = true
version.workspace = true

[dependencies]
salsa-2022.workspace = true
thiserror.workspace = true
eyre.workspace = true
miette.workspace = true
im.workspace = true
